### ISSUE TITLE
Aranet Firmware >= 1.2 no longer works with this plugin

### ISSUE THREAD

**Issue by ParaAdBellum** [quentinms/homebridge-aranet4#15]
It appears that they changed service UUID, and hence the one this plugin uses no longer works with latest firmware. see

https://forum.aranet.com/all-about-aranet4/aranet4-with-firmware-v.1.2.0-or-greater-integration-notes/

**Comment by ParaAdBellum** [comment]
changing ARANET4_SERVICE to seems to do the trick
const ARANET4_SERVICE = 'fce0';

**Comment by quentinms** [comment]
Thanks a lot for reporting this! I had not noticed as I had upgraded my firmware yet.

It should be fixed with #16, and I'll tag a new release.
