### ISSUE TITLE
Pull out CO2 reading into a gauge?

### ISSUE THREAD

**Issue by finestructure** [quentinms/homebridge-aranet4#21]
In the default configuration, the Aranet4 sensors are displayed as follows in the Home app:

<img width="380" alt="CleanShot 2022-12-12 at 10 07 35@2x" src="https://user-images.githubusercontent.com/65520/207006076-da13a806-428a-4500-a6b6-b9306418510f.png">

This may not be possible to do via the plugin but I'd love to get the CO2 reading in a gauge, just like the temperature and humidity displays.

I can drill into the "sensor" to see the value but that's a bit awkward:

![CleanShot 2022-12-12 at 10 07 46@2x](https://user-images.githubusercontent.com/65520/207006322-34f890a8-54b4-451d-bd04-10a21b7fa48f.png)

Is this possible to do somehow?

**Comment by quentinms** [comment]
As far as I can tell, this is a Homekit limitation. 

I provide the data and Apple decides how to display it.

I use https://developers.homebridge.io/#/service/CarbonDioxideSensor (which maps to https://developer.apple.com/documentation/homekit/hmcharacteristictypecarbondioxidelevel).

Looks like they modeled the DioxideSensor after the MonoxideSensor that also only has triggered/not-triggered states.

Best suggestion I can offer is complain to Apple: https://www.apple.com/feedback/home-app/

**Comment by finestructure** [comment]
I see, thanks for taking a look!
